suricata: update suricata and suricata-update init scripts and configs
Updated suricata and Suricata-update init scripts and config files
Signed-off-by: Ashkan Jazayeri <ashkan@jazayeri.net>

diff --git a/net/suricata6/files/etc/init.d/suricata-update b/net/suricata6/files/etc/init.d/suricata-update
--- a/net/suricata6/files/etc/init.d/suricata-update
+++ b/net/suricata6/files/etc/init.d/suricata-update
@@ -1,4 +1,5 @@
 #!/bin/sh /etc/rc.common
+# Copyright (C) 2021 Ashkan Jazayeri <ashkan@jazayeri.net>
 
 START=99
 STOP=10
@@ -7,40 +8,48 @@ USE_PROCD=1
 PROG=/usr/bin/suricata-update
 
 validate_suricata_section() {
-        uci_load_validate suricata update "$1" "$2" \
-                'rulespath:string' \
-                'reload:bool' \
-                'add_sources_on_startup:bool' \
-                'enabled:bool'
+	uci_load_validate suricata update "$1" "$2" \
+		'rulespath:string' \
+		'defaultpath:string:/var/lib/suricata' \
+		'reload_suricata:bool:1' \
+		'enable_sources:bool:1' \
+		'update_source_list:bool:1'
 }
 
-start_service() {
-        config_load suricata
-        config_get rulespath update rulespath
-        config_get reload update reload
-        config_get add_sources_on_startup update add_sources_on_startup
-        config_get enabled update enabled
+enable_list() {
+	suricata-update enable-source $1 -D $defaultpath
+}
 
-        validate_suricata_section suricata || {
-                echo "validation failed"
-                return 1
-        }
+start_suricata_update() {
+	validate_suricata_section suricata || {
+		echo "validation failed"
+		return 1
+	}
 
-        procd_open_instance
-	[ $rulespath = "/var/lib/suricata/rules" ] && \
-	  procd_set_param command $PROG --reload-command "/etc/init.d/suricata restart"  || \
-	  procd_set_param command $PROG -o $rulespath --reload-command "/etc/init.d/suricata restart"
-        procd_close_instance
+	[ $update_source_list -eq "1" ] && \
+		suricata-update update-sources -D $defaultpath
+	[ $enable_sources -eq "1" ] && \
+		config_list_foreach update sources enable_list
+
+	procd_open_instance
+	[ $defaultpath ] && procd_append_param command -D $defaultpath
+	[ $rulespath ] && procd_append_param command -o $rulespath
+	[ $reload_suricata -eq "1" ] && procd_append_param command --reload-command '/etc/init.d/suricata reload'
+	procd_close_instance
 }
 
 stop_service()
 {
-        service_stop ${PROG}
+	service_stop ${PROG}
+}
+
+start_service() {
+	validate_suricata_section update start_suricata_update
 }
 
 service_triggers()
 {
-        procd_add_reload_trigger "suricata-update"
-        procd_add_validation validate_suricata_section
+	procd_add_reload_trigger "suricata-update"
+	procd_add_validation validate_suricata_section
 }
 
